# src/agent/state.py

from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    """
    State tracking schema passed between nodes in the MediQwen LangGraph network.
    """
    # 1. Inputs & Image Payloads from User
    user_query: str                         # Raw conversational text or medical question
    image_path: Optional[str]               # Local path to an uploaded medical image asset
    process_image: bool                     # Authorized flag set by Dialogue Manager for Turn 1 image processing
    processed_image_payload: Optional[str] # Base64-encoded processed image data for direct LLM vision
    is_online: bool                         # Toggle mapping: True allows live Web Search tool fallback

    # 2. Dialogue FSM & Deferred RAG Tracking
    dialog_state: str                       # Active state: 'chat', 'multimodal_triage', 'clinical', 'closing', 'blocked'
    requires_retrieval: bool               # Decoupled flag: True strictly when clinical knowledge retrieval is requested
    clinical_subject: Optional[str]        # Extracted concept (e.g., 'urticaria', 'eczema') to resolve multi-turn queries
    followup_pending: bool                 # Tracks if assistant offered choices on Turn 1 awaiting user response
    
    # 3. Calculated Safety & Triage Parameters
    risk_level: str                         # Evaluation from classifier: low, medium, high, emergency
    risk_metadata: Dict[str, Any]           # Specific triage metrics (triggers, score, emergency protocol)
    is_safe: bool                           # Safety guardrail check flag
    intent: str                             # Classified intent from dialogue manager
    top_retrieval_distance: float          # Best match distance score from vector search
    
    # 4. Contextual Data Pipelines
    retrieved_context: List[str]            # Context text chunks extracted via ChromaDB or live web fallback
    context_sources: List[str]              # Provenance references (URLs, documents, visual payload tags)
    retrieval_query: Optional[str]          # Resolved search query executed against vector collection
    
    # 5. Final Output Compilation
    agent_response: str                     # Clinical or conversational response generated by MediQwen
    routing_trace: List[str]                # Execution node history array for telemetric debugging and auditing
    show_risk_badge: bool                    # Flag indicating whether UI should display a triage risk badge