# src/agent/state.py

from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    """
    State tracking schema passed between nodes in the MediGemma LangGraph network.
    """
    # 1. Inputs from the user
    user_query: str                  # The raw conversational text or medical question
    image_path: Optional[str]        # Local path to an uploaded image/report (X-ray, PDF, etc.)
    process_image: bool                # Flag to indicate if the image should be processed
    processed_image_payload: Optional[str]  # Base64-encoded processed image data for multimodal analysis
    is_online: bool                  # Toggle mapping: True allows Web Search tool fallback if RAG drops
    dialog_state: str
    
    # 2. Calculated Safety & Triage parameters
    risk_level: str                  # Evaluation from classifier: low, medium, high, emergency
    risk_metadata: Dict[str, Any]    # Specific context metrics (triggers, score, actions)
    is_safe: bool 
    intent: str                      # Classified intent from the local LLM
    top_retrieval_distance: float   # Distance threshold for top retrieval results
    
    # 3. Contextual Data Pipelines
    retrieved_context: List[str]     # Combined whole string text chunks extracted via RAG or Web
    context_sources: List[str]       # Traceable URLs or filenames backing the clinical data
    
    # 4. Final Output Compilation
    agent_response: str              # Hardened medical response generated by Gemma and 
    routing_trace: List[str]         # Optional list of nodes traversed in the LangGraph execution for debugging and audit purposes
    show_risk_badge: bool             # Flag to indicate if the UI should display a risk badge based on the risk_level